name: Test

on:
  pull_request:
    branches:
      - master
      - development

permissions: read-all

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        platform: [ macos-latest, ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Rust fmt
        run: cargo fmt -- --check

      - name: Cargo check
        run: cargo check
